language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: danscode@selman.org
  api_key:
    secure: GFABi0jztXUGJLmIT1CMFlPeI/CV6acitk4DToA80UYZh88ONKx8Or7ipYQKisjPmQMKd1xLiUu2J4S4amhktmOfB3IJf4ZUdPfh7U1E2ESTLIwBjlXbJA9XLPhEkOcHeU91ZgRYI9cPPbCH4LR8LHQPcu7gRg11ApGVVq+zSdaEj+hrIbH8T3m8ZLVwcivfI92YgnQqY3+5S9UYUGt3cEVT1cPlNlpFn01Hpvfqo1x0hPOOT/Q4yavhc10wyvKc/iuw8QZV+tt+vlzytraldVhC6zojPDx3elk1soz/cFIWNFNi7GZJQuEUS02X9jVuCVapH48DI1J4xUxTj3tQvuLK8q31XHR5Uj6OWZQ3miGLRYRAGXAQKdOwPMK8ptOTs+RrA1sOae6R7+wCtWWvYh89SI2Q0ihLZVS7Faig7OE3YZXYIB5166QYfC5iY4N8t1r2fzJnrf/AOWuS/qiK24E23QAgG5bl+txUtV9DuVRqkDLK5pmJa93mianH+OsHTS9Pgz05o5qgJEvBmzuGGX17NwYCvHBmqtU6b0YokeLPuDF+ZCw6sWjyV2/qaTUl5UVB6xHjUO4xRsp9zdXQy6ki13RxzZ1ItclD9HWHqCpr0PKkdGF+1D9j+UODFvjz5fhPvGfwfKNOAl2nlly9ugJTi4uSpyAj4LBp7DGSZNE=
  on:
    tags: true
    repo: dselman/composer-concerto
